name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: SSH Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "latest" # option
          requirements: "requirements.txt" # option
          configfile: "mkdocs.yml" # option

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./site/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
