name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: SSH Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: Tiryoh/actions-mkdocs@v0
        with:
          mkdocs_version: "latest" # option
          requirements: "requirements.txt" # option
          configfile: "mkdocs.yml" # option

      - name: Publish
        uses: dennisameling/ftp-upload-action@v1
        with:
          local_dir: ./site/
          server: ${{ secrets.FTP_SERVER }}
          server_dir: ${{ secrets.FTP_SERVER_PATH }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
